#encoding: utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Feed.create(name: "Ca se passe la haut", url: "http://drericsimon.blogspot.com/feeds/posts/default?alt=rss")
Feed.create(name: "Choux romanesco, vache qui rit et intégrales curvilignes", url: "http://eljjdx.canalblog.com/rss.xml")
Feed.create(name: "Du côté de chez Elysia chlorotica", url: "http://du-cote-de-chez-elysia-chlorotica.blogspot.com/feeds/posts/default?alt=rss")
Feed.create(name: "Homo Fabulus", url: "http://feeds.feedburner.com/HomoFabulus")
Feed.create(name: "Strip Science", url: "http://stripscience.cafe-sciences.org/articles/category/inedit-strip-science/feed/")
Feed.create(name: "Kidiscience", url: "http://kidiscience.cafe-sciences.org/feed/")
Feed.create(name: "Science infuse", url: "http://blog.science-infuse.fr/feed/atom")
Feed.create(name: "Le bloug", url: "http://www.lebloug.fr/index.php/feed/")
Feed.create(name: "Dinosauria", url: "http://www.dinosauria.org/blog/feed/")
Feed.create(name: "Le monde et nous", url: "http://lemondeetnous.cafe-sciences.org/feed/")
Feed.create(name: "Le Webinet des curiosités", url: "http://webinet.cafe-sciences.org/feed/")
Feed.create(name: "Dessous des sciences", url: "http://dessousdescience.cafe-sciences.org/feed/")
Feed.create(name: "Math et physique", url: "http://www.maths-et-physique.net/rss2.php")
Feed.create(name: "Fish don't exist", url: "http://fish-dont-exist.blogspot.com/feeds/posts/default")
Feed.create(name: "Tom Roud", url: "http://tomroud.cafe-sciences.org/feed/")
Feed.create(name: "Dossiers podcastscience", url: "http://www.podcastscience.fm/category/dossiers/feed/")
Feed.create(name: "Quizz podcastscience", url: "http://www.podcastscience.fm/category/quizz-info-ou-intox/feed")
Feed.create(name: "Dr Goulu", url: "http://feeds.feedburner.com/drgoulu")
Feed.create(name: "Pourquoi le ciel est bleu", url: "http://pourquoilecielestbleu.cafe-sciences.org/feed/")
Feed.create(name: "Rock'n'science", url: "http://sproutchlagrenouille.wordpress.com/feed/")
Feed.create(name: "Science étonnante", url: "http://sciencetonnante.wordpress.com/feed/")
Feed.create(name: "Sham and science", url: "http://blogs.univ-poitiers.fr/n-yeganefar/feed/")
Feed.create(name: "Sirtin", url: "http://sirtin.cafe-sciences.org/feed/")
Feed.create(name: "Strange Stuf and Funky Things", url: "http://ssaft.com/Blog/dotclear/index.php?feed/tag/Science/atom")
Feed.create(name: "Sweet random Science", url: "http://sweetrandomscience.blogspot.com/feeds/posts/default")
Feed.create(name: "Tout se passe comme si", url: "http://toutsepassecommesi.cafe-sciences.org/feed/")
Feed.create(name: "A la main", url: "http://www.alamain.info/?feed=rss2")
Feed.create(name: "Recherche en cours", url: "http://www.rechercheencours.fr/REC/Blogcast/rss.xml")
Feed.create(name: "A la source", url: "http://alasource.blog.lemonde.fr/feed/")
Feed.create(name: "anthropoblog", url: "http://www.anthropoblog.fr/?feed=rss2")
Feed.create(name: "association café des sciences", url: "http://association.cafe-sciences.org/feed/rss2")
Feed.create(name: "Biopsci", url: "http://feeds2.feedburner.com/Biopsci")
Feed.create(name: "xenius", url: "http://xenius.arte.tv/blog/category/actualites/feed")
Feed.create(name: "Sciences le monde", url: "http://sciences.blog.lemonde.fr/feed/")
Feed.create(name: "idPhys", url: "http://blog.idphys.fr/category/blog-2/feed/")
Feed.create(name: "Le blogue de valérie Borde", url: "http://www.lactualite.com/opinions/le-blogue-de-valerie-borde/feed/")
Feed.create(name: "Dvanw", url: "http://dvanw.blogspot.com/feeds/posts/default/-/sciences")
Feed.create(name: "La science pour tous", url: "http://lasciencepourtous.cafe-sciences.org/feed/")
Feed.create(name: "Enroweb", url: "http://www.enroweb.com/blogsciences/rss.php")
Feed.create(name: "iceblog", url: "http://iceblog.over-blog.com/atom.php")
Feed.create(name: "svtcolin", url: "http://svtcolin.blogspot.com/feeds/posts/default")
Feed.create(name: "bacterioblog", url: "http://www.bacterioblog.com//?feed=rss2")
Feed.create(name: "Le comptoir du café des sciences", url: "http://comptoir.cafe-sciences.org/feed/")
Feed.create(name: "Le journal des chouettes savantes", url: "http://lejournaldeschouettessavantes.cafe-sciences.org/feed/")
Feed.create(name: "Making Science Public", url: "http://feeds.feedburner.com/MakingSciencePublic")
Feed.create(name: "Prisme de tête", url: "http://www.prismedetete.net/feed/atom/")
Feed.create(name: "Podcast Recherche en cours", url: "http://www.rechercheencours.fr/REC/Podcast/rss.xml")
Feed.create(name: "Science et conscience", url: "http://scienceetconscience.wordpress.com/feed/")
Feed.create(name: "votons science", url: "http://votonsscience.blog.lemonde.fr/feed/")


User.create(email: "nicolas.tupecabet@gmail.com", password: "12345678", password_confirmation: '12345678')
